#!/bin/sh

set -eu
cp -r tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

export XDG_RUNTIME_DIR="$AUTOPKGTEST_TMP"

for python in $(py3versions -s); do
    echo "Testing with $python..."
    dbus-run-session -- $python -m unittest discover -v -s tests
done
